import type { Metadata } from "next";

import "./globals.css";
import AppProvider from "@/providers/app-provider";
import { cn } from "@/lib/utils";
import { Zain } from "next/font/google";

const zain = Zain({
  display: "swap",
  subsets: ["arabic"],
  weight: ["200", "300", "400", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "نظام عافية الصحي",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
      <body
        lang="ar"
        dir="rtl"
        suppressHydrationWarning
        className={(cn("antialiased"), zain.className)}
      >
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
